export const products = [
    { id: 1, name: "Smartphone", price: 699,discount1: 650, discount2: 600, rating: 4.5, category: "Electronics", brand: "Lenovo", image: "/src/assets/images/details/phone.png" },
    { id: 2, name: "Laptop", price: 999,discount1: 950, discount2: 900,  rating: 4.7, category: "Electronics", brand: "Apple", image: "/src/assets/images/details/laptop.png" },
    { id: 3, name: "T-Shirt", price: 100, discount1: 70, discount2: 50, rating: 4.1, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/shirt.png" },
    { id: 4, name: "Blender", price: 499,discount1: 390, discount2: 350,  rating: 4.2, category: "Home Appliances", brand: "Sony", image: "/src/assets/images/details/blender.png" },
    { id: 5, name: "Brown Leather Jacket", price: 89, discount1: 80, discount2: 70, rating: 4.6, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/shirt3.png" },
    { id: 6, name: "Apple Watch", price: 500,discount1: 450, discount2: 400,  rating: 4.8, category: "Electronics", brand: "Apple", image: "/src/assets/images/details/smartWatch.png" },
    { id: 7, name: "Smartphone", price: 699,discount1: 650, discount2: 600,  rating: 4.5, category: "Electronics", brand: "Samsung", image: "/src/assets/images/details/phone3.png" },
    { id: 8, name: "Electric chopper", price: 500,discount1: 450, discount2: 410,  rating: 4.7, category: "Electronics", brand: "Sony", image: "/src/assets/images/details/chopper.png" },
    { id: 9, name: "Blue T-Shirt", price: 50, discount1: 40, discount2: 35, rating: 4.1, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/shirt2.png" },
    { id: 10, name: "Tablet", price: 499,discount1: 449, discount2: 400,  rating: 4.2, category: "Electronics", brand: "Samsung", image: "/src/assets/images/details/phone2.png" },
    { id: 11, name: "Nike Shoes", price: 150, discount1: 130, discount2: 100, rating: 4.6, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/shoes.jpg" },
    { id: 12, name: "Vaccuum Cleaner", price: 499,discount1: 450, discount2: 400,  rating: 4.8, category: "Home Appliances", brand: "Sony", image: "/src/assets/images/details/vaccuum.jpg" },
    { id: 13, name: "Blue Suit", price: 200, discount1: 190, discount2: 170, rating: 4.1, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/suit.png" },
    { id: 14, name: "Ipad Pro", price: 699,discount1: 650, discount2: 600,  rating: 4.2, category: "Electronics", brand: "Apple", image: "/src/assets/images/details/ipad.jpg" },
    { id: 15, name: "Nike Shoes", price: 150, discount1: 130, discount2: 100, rating: 4.6, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/shoes2.jpeg" },
    { id: 16, name: "Microwave Oven", price: 499,discount1: 449, discount2: 400,  rating: 4.8, category: "Home Appliances", brand: "Sony", image: "/src/assets/images/details/oven.jpg" },
    { id: 17, name: "Blue leather wallet", price: 70, discount1: 60, discount2: 50, rating: 4.6, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/wallet.png" },
    { id: 18, name: "Headphones", price: 200,discount1: 170, discount2: 150,  rating: 4.8, category: "Electronics", brand: "Sony", image: "/src/assets/images/details/headphone2.png" },
    { id: 19, name: "RC Drone", price: 800, discount1: 750, discount2: 730, rating: 4.1, category: "Modern Tech", brand: "Lenovo", image: "/src/assets/images/details/drone.jpg" },
    { id: 20, name: "Gaming headphones", price: 400,discount1: 350, discount2: 300,  rating: 4.2, category: "Electronics" , brand: "Apple", image: "/src/assets/images/details/headphones.png" },
    { id: 21, name: "Blue Jeans Bag", price: 150, discount1: 130, discount2: 100, rating: 4.6, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/bag.png" },
    { id: 22, name: "Electric Kettle", price: 200,discount1: 150, discount2: 100,  rating: 4.8, category: "Home Appliances", brand: "Sony", image: "/src/assets/images/details/kettle.png" },
    { id: 23, name: "Jeans Shorts", price: 70, discount1: 60, discount2: 50, rating: 4.6, category: "Clothing", brand: "Nike", image: "/src/assets/images/details/short.png" },
    { id: 24, name: "Canon Camera", price: 499,discount1: 449, discount2: 400,  rating: 4.8, category: "Modern tech", brand: "Sony", image: "/src/assets/images/details/goproCamera.png" },
    { id: 25, name: "Rice Cooker", price: 400, discount1: 350, discount2: 300, rating: 4.1, category: "Home Appliances", brand: "Sony", image: "/src/assets/images/details/rice.jpeg" },
    { id: 26, name: "Earpods", price: 400,discount1: 350, discount2: 300,  rating: 4.2, category: "Modern tech" , brand: "Apple", image: "/src/assets/images/details/airpods.jpg" },
    { id: 27, name: "Washing Machine", price: 700, discount1: 780, discount2: 750, rating: 4.6, category: "Home Appliances", brand: "Sony", image: "/src/assets/images/details/machine.jpeg" },
    { id: 28, name: "Hair Dryer", price: 200,discount1: 150, discount2: 100,  rating: 4.8, category: "Modern tech", brand: "Sony", image: "/src/assets/images/details/dryer.jpeg" },
    { id: 29, name: "Air purifier", price: 200, discount1: 150, discount2: 130, rating: 4.6, category: "Home Appliances", brand: "Nike", image: "/src/assets/images/details/purifier.jpg" },
    { id: 30, name: "Gaming mouse", price: 499,discount1: 449, discount2: 400,  rating: 4.8, category: "Modern tech", brand: "Sony", image: "/src/assets/images/details/mouse.jpg" },
  ];
  